### Получить конкретного пользователя
GET http://localhost:3000/users/61103f22c637256b3a877d0a
Accept: application/json

### Получить всех пользователей
GET http://localhost:3000/users/
Accept: application/json

### Создать пользователя
POST http://localhost:3000/users/
Content-Type: application/json
Accept: application/json

{
  "name": "user 2",
  "about": "about 2"
}

